import { Post } from './types'


export const SAMPLE_POSTS: Post[] = [
	{
		id: 'p1',
		title: 'AI thay đổi ngành y tế như thế nào?',
		author: 'Nguyễn Văn An',
		thumbnail: 'https://picsum.photos/seed/aihealth/400/250',
		content: 'Trí tuệ nhân tạo đang giúp chẩn đoán bệnh nhanh hơn, chính xác hơn và hỗ trợ bác sĩ trong điều trị. Các hệ thống AI có thể phân tích hình ảnh y tế, dự đoán nguy cơ bệnh và cá nhân hóa phác đồ điều trị cho từng bệnh nhân.',
		category: 'Công nghệ',
		createdAt: '2025-10-20T08:30:00.000Z',
	},
	{
		id: 'p2',
		title: 'Top 5 địa điểm du lịch nổi bật ở Việt Nam',
		author: 'Lê Thị Bích',
		thumbnail: 'https://picsum.photos/seed/vietnamtravel/400/250',
		content: 'Việt Nam có nhiều điểm đến hấp dẫn như Sa Pa, Đà Nẵng, Hội An, Phú Quốc và Ninh Bình. Mỗi nơi đều có nét đẹp riêng về thiên nhiên, văn hóa và ẩm thực.',
		category: 'Du lịch',
		createdAt: '2025-10-19T10:15:00.000Z',
	},
	{
		id: 'p3',
		title: 'Bí quyết học lập trình hiệu quả',
		author: 'Trần Minh Cường',
		thumbnail: 'https://picsum.photos/seed/code/400/250',
		content: 'Để học lập trình tốt, bạn nên thực hành nhiều, tham gia các dự án thực tế, đọc tài liệu tiếng Anh và không ngại hỏi khi gặp khó khăn.',
		category: 'Công nghệ',
		createdAt: '2025-10-18T14:00:00.000Z',
	},
	{
		id: 'p4',
		title: 'Cách làm bánh mì Việt Nam chuẩn vị',
		author: 'Phạm Thị Dung',
		thumbnail: 'https://picsum.photos/seed/banhmi/400/250',
		content: 'Bánh mì Việt Nam nổi tiếng với lớp vỏ giòn, ruột mềm và nhân đa dạng. Bí quyết là nướng ở nhiệt độ cao và chọn nguyên liệu tươi ngon.',
		category: 'Ẩm thực',
		createdAt: '2025-10-17T09:45:00.000Z',
	},
	{
		id: 'p5',
		title: 'Sống tối giản: Bắt đầu từ đâu?',
		author: 'Võ Quang Huy',
		thumbnail: 'https://picsum.photos/seed/minimal/400/250',
		content: 'Sống tối giản giúp bạn tập trung vào những điều quan trọng, giảm căng thẳng và tiết kiệm chi phí. Hãy bắt đầu bằng việc loại bỏ những vật dụng không cần thiết.',
		category: 'Đời sống',
		createdAt: '2025-10-16T11:20:00.000Z',
	},
	{
		id: 'p6',
		title: 'Review quán cà phê đẹp ở Hà Nội',
		author: 'Nguyễn Thị Lan',
		thumbnail: 'https://picsum.photos/seed/cafehanoi/400/250',
		content: 'Hà Nội có nhiều quán cà phê đẹp như Tranquil, The Coffee House, Cộng Cà Phê... Không gian yên tĩnh, thích hợp làm việc và gặp gỡ bạn bè.',
		category: 'Ẩm thực',
		createdAt: '2025-10-15T15:10:00.000Z',
	},
	{
		id: 'p7',
		title: 'Hướng dẫn du lịch Đà Lạt tự túc',
		author: 'Lê Văn Sơn',
		thumbnail: 'https://picsum.photos/seed/dalat/400/250',
		content: 'Đà Lạt nổi tiếng với khí hậu mát mẻ, cảnh đẹp và nhiều điểm check-in như Hồ Xuân Hương, Thung lũng Tình Yêu, vườn hoa thành phố.',
		category: 'Du lịch',
		createdAt: '2025-10-14T13:00:00.000Z',
	},
	{
		id: 'p8',
		title: 'Cách quản lý tài chính cá nhân thông minh',
		author: 'Phan Thanh Tùng',
		thumbnail: 'https://picsum.photos/seed/finance/400/250',
		content: 'Quản lý tài chính cá nhân hiệu quả giúp bạn tiết kiệm, đầu tư và tránh nợ xấu. Hãy lập kế hoạch chi tiêu và theo dõi các khoản thu chi hàng tháng.',
		category: 'Đời sống',
		createdAt: '2025-10-13T17:30:00.000Z',
	},
	{
		id: 'p9',
		title: 'Những cuốn sách nên đọc năm 2025',
		author: 'Đỗ Thị Mai',
		thumbnail: 'https://picsum.photos/seed/book2025/400/250',
		content: 'Một số cuốn sách nổi bật: "Dám bị ghét", "Atomic Habits", "Tư duy nhanh và chậm"... giúp phát triển bản thân và mở rộng kiến thức.',
		category: 'Đời sống',
		createdAt: '2025-10-12T08:00:00.000Z',
	},
	{
		id: 'p10',
		title: 'Công nghệ blockchain ứng dụng thực tế',
		author: 'Ngô Văn Phúc',
		thumbnail: 'https://picsum.photos/seed/blockchain/400/250',
		content: 'Blockchain không chỉ dùng cho tiền mã hóa mà còn ứng dụng trong quản lý chuỗi cung ứng, bảo mật dữ liệu và hợp đồng thông minh.',
		category: 'Công nghệ',
		createdAt: '2025-10-11T19:40:00.000Z',
	},
	{
		id: 'p11',
		title: 'Món ăn đường phố Sài Gòn',
		author: 'Trần Quốc Bảo',
		thumbnail: 'https://picsum.photos/seed/saigonfood/400/250',
		content: 'Sài Gòn nổi tiếng với các món ăn như bánh tráng trộn, hủ tiếu, cơm tấm, gỏi cuốn... Giá cả phải chăng và hương vị đặc trưng.',
		category: 'Ẩm thực',
		createdAt: '2025-10-10T12:00:00.000Z',
	},
	{
		id: 'p12',
		title: '5 mẹo tăng năng suất làm việc',
		author: 'Nguyễn Văn Hùng',
		thumbnail: 'https://picsum.photos/seed/productivity/400/250',
		content: 'Đặt mục tiêu rõ ràng, ưu tiên công việc, nghỉ giải lao hợp lý, sử dụng công cụ quản lý thời gian và tránh đa nhiệm giúp tăng hiệu quả làm việc.',
		category: 'Đời sống',
		createdAt: '2025-10-09T09:00:00.000Z',
	},
	{
		id: 'p13',
		title: 'Hướng dẫn sử dụng React cho người mới',
		author: 'Lê Minh Đạt',
		thumbnail: 'https://picsum.photos/seed/reactjs/400/250',
		content: 'React là thư viện JavaScript phổ biến để xây dựng giao diện web. Bài viết hướng dẫn cài đặt, tạo component và quản lý state cơ bản.',
		category: 'Công nghệ',
		createdAt: '2025-10-08T16:00:00.000Z',
	},
	{
		id: 'p14',
		title: 'Du lịch Huế: Khám phá cố đô',
		author: 'Phạm Thị Hoa',
		thumbnail: 'https://picsum.photos/seed/hue/400/250',
		content: 'Huế nổi tiếng với Đại Nội, lăng tẩm vua chúa và ẩm thực đặc sắc như bún bò Huế, bánh bèo, chè Huế.',
		category: 'Du lịch',
		createdAt: '2025-10-07T11:00:00.000Z',
	},
	{
		id: 'p15',
		title: 'Cách bảo vệ sức khỏe mùa lạnh',
		author: 'Nguyễn Thị Mai',
		thumbnail: 'https://picsum.photos/seed/health/400/250',
		content: 'Giữ ấm cơ thể, ăn uống đủ chất, tập thể dục đều đặn và bổ sung vitamin C giúp tăng sức đề kháng trong mùa lạnh.',
		category: 'Đời sống',
		createdAt: '2025-10-06T08:00:00.000Z',
	},
	{
		id: 'p16',
		title: 'Ẩm thực miền Tây: Đặc sản không thể bỏ qua',
		author: 'Lê Văn Phát',
		thumbnail: 'https://picsum.photos/seed/mientay/400/250',
		content: 'Miền Tây nổi tiếng với các món như cá lóc nướng trui, bánh xèo, lẩu mắm... Đặc sản đậm đà hương vị quê hương.',
		category: 'Ẩm thực',
		createdAt: '2025-10-05T18:00:00.000Z',
	},
	{
		id: 'p17',
		title: 'Du lịch Phú Quốc: Kinh nghiệm và lưu ý',
		author: 'Trần Thị Kim',
		thumbnail: 'https://picsum.photos/seed/phuquoc/400/250',
		content: 'Phú Quốc có biển xanh, cát trắng, nhiều resort sang trọng và các hoạt động như lặn biển, câu cá, tham quan đảo.',
		category: 'Du lịch',
		createdAt: '2025-10-04T14:00:00.000Z',
	},
	{
		id: 'p18',
		title: 'Cách học tiếng Anh giao tiếp hiệu quả',
		author: 'Nguyễn Văn Tâm',
		thumbnail: 'https://picsum.photos/seed/english/400/250',
		content: 'Luyện nghe, nói hàng ngày, tham gia câu lạc bộ tiếng Anh và sử dụng ứng dụng học tiếng giúp cải thiện kỹ năng giao tiếp.',
		category: 'Đời sống',
		createdAt: '2025-10-03T20:00:00.000Z',
	},
	{
		id: 'p19',
		title: 'Tổng hợp các framework web phổ biến',
		author: 'Phạm Văn Nam',
		thumbnail: 'https://picsum.photos/seed/framework/400/250',
		content: 'Các framework web nổi bật: React, Angular, Vue, Svelte... Mỗi framework có ưu điểm riêng về tốc độ, cộng đồng và khả năng mở rộng.',
		category: 'Công nghệ',
		createdAt: '2025-10-02T09:00:00.000Z',
	},
	{
		id: 'p20',
		title: 'Khám phá ẩm thực đường phố Hà Nội',
		author: 'Lê Thị Thu',
		thumbnail: 'https://picsum.photos/seed/hanoifood/400/250',
		content: 'Hà Nội có nhiều món ngon như phở, bún chả, bánh cuốn, chả cá... Đặc biệt, các quán ăn vỉa hè mang lại trải nghiệm thú vị.',
		category: 'Ẩm thực',
		createdAt: '2025-10-01T07:00:00.000Z',
	},
]